//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Abogados_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abogado
    {
        public long Id_Abogado { get; set; }
        public string Nombre_Completo { get; set; }
        public string Experinecia { get; set; }
        public long Id_Especialidad { get; set; }
        public string Correo_Electronico { get; set; }
        public int Telefono { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
    }
}
