//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Abogados_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long Id_Bitacora { get; set; }
        public System.DateTime Fecha_Hora { get; set; }
        public string Mensaje { get; set; }
        public string Origen { get; set; }
        public long Id_Usuario { get; set; }
        public string Direccion_IP { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
